(* Helper: export a dated prediction plot under predictions/, refresh -latest copies,
   and write companion markdown (dated + latest) with optional metrics.
   Requires `base` (notebook directory, with trailing slash) to be set.
   Load with: Get[base <> "PredictionsExport.wl"]

   Note: `-latest.png` / `-latest.md` are regular file copies (not symlinks). GitHub's
   README renderer does not reliably follow symlinks for images. *)

ClearAll[exportPrediction, formatPredictionMarkdown, updatePredictionsLatestIndex];

(* Preferred display order in predictions/LATEST.md *)
$predictionStemOrder = {
  "BTC_Overvaluation-P",
  "BTC_Overvaluation-NP",
  "BTC_PricePrediction",
  "Gold(PAXG)_PricePrediction",
  "Silver(KAG)_PricePrediction"
};

formatPredictionMarkdown[nameStem_String, date_String, imageFile_String, meta_Association] := Module[
  {lines, keys, k, v},
  lines = {
    "# " <> nameStem,
    "",
    "![" <> nameStem <> "](./" <> imageFile <> ")",
    "",
    "- **As of:** " <> date
  };
  keys = DeleteCases[Keys[meta], "As of" | "as of" | "Date" | "date"];
  Do[
    v = meta[k];
    AppendTo[lines, "- **" <> ToString[k] <> ":** " <> ToString[v]],
    {k, keys}
  ];
  AppendTo[lines, ""];
  StringRiffle[lines, "\n"]
];

updatePredictionsLatestIndex[dir_String] := Module[
  {files, stems, ordered, rest, body, path},
  files = FileNames["*-latest.md", dir];
  stems = StringReplace[FileNameTake /@ files, "-latest.md" -> ""];
  stems = DeleteCases[stems, "LATEST"];
  ordered = Select[$predictionStemOrder, MemberQ[stems, #] &];
  rest = Sort[Complement[stems, ordered]];
  body = StringRiffle[
    Join[
      {
        "# Latest predictions",
        "",
        "Auto-generated by `PredictionsExport.wl`. Companion metrics for the gallery plots.",
        "",
        "*Research / educational only. Not investment advice.*",
        ""
      },
      Flatten[
        Function[stem,
          {
            "## " <> stem,
            "",
            (* Pull body after the H1 from each fragment *)
            StringTrim @ StringReplace[
              Import[FileNameJoin[{dir, stem <> "-latest.md"}], "Text"],
              StartOfString ~~ "# " ~~ stem ~~ "\n" -> ""
            ],
            ""
          }
        ] /@ Join[ordered, rest]
      ]
    ],
    "\n"
  ];
  path = FileNameJoin[{dir, "LATEST.md"}];
  Export[path, body, "Text"];
  path
];

(* meta: Association of metric labels -> values, e.g.
   <|"Fair price" -> "$42k", "Market" -> "$68k", "Overvaluation" -> "62%"|> *)
exportPrediction[plot_, nameStem_String, date_String] :=
  exportPrediction[plot, nameStem, date, <||>];

exportPrediction[plot_, nameStem_String, date_String, meta_Association] := Module[
  {dir, datedPng, latestPng, datedMd, latestMd, datedPngPath, latestPngPath,
   datedMdPath, latestMdPath, mdDated, mdLatest},
  dir = base <> "predictions";
  CreateDirectory[dir, CreateIntermediateDirectories -> True];
  datedPng = nameStem <> "-" <> date <> ".png";
  latestPng = nameStem <> "-latest.png";
  datedMd = nameStem <> "-" <> date <> ".md";
  latestMd = nameStem <> "-latest.md";
  datedPngPath = FileNameJoin[{dir, datedPng}];
  latestPngPath = FileNameJoin[{dir, latestPng}];
  datedMdPath = FileNameJoin[{dir, datedMd}];
  latestMdPath = FileNameJoin[{dir, latestMd}];

  Export[datedPngPath, plot];
  If[FileExistsQ[latestPngPath] || DirectoryQ[latestPngPath], DeleteFile[latestPngPath]];
  CopyFile[datedPngPath, latestPngPath];

  mdDated = formatPredictionMarkdown[nameStem, date, datedPng, meta];
  mdLatest = formatPredictionMarkdown[nameStem, date, latestPng, meta];
  Export[datedMdPath, mdDated, "Text"];
  Export[latestMdPath, mdLatest, "Text"];

  updatePredictionsLatestIndex[dir];

  {datedPngPath, latestPngPath, datedMdPath, latestMdPath}
];

(* Examples (after plots are built):
exportPrediction[bitcoinOvervaluation, "BTC_Overvaluation-P", last,
  <|"Fair price" -> fairPrice, "Market" -> marketPrice, "Overvaluation" -> overPct|>]
exportPrediction[bitcoinOvervaluationNp, "BTC_Overvaluation-NP", last,
  <|"Fair price" -> fairPriceNp, "Market" -> marketPrice, "Overvaluation" -> overPctNp|>]
exportPrediction[pricePlot, "BTC_PricePrediction", lastPriceDate,
  <|"Critical time tc" -> tc, "p-value" -> p|>]
*)
